#!/bin/bash

read -p "unique login (e.g. nickname): " uid
read -p "surename name: " name
read -s -p "password: " password
read -p "email: " email

mysql -h mysql -u root -p${MYSQL_ROOT_PASSWORD} -D sogo -e "INSERT INTO sogo_users VALUES ('${uid}', '${uid}', MD5('${password}'), '${name}', '${email}');"
